name: Continous Integration and Testing

on:
  push:
    branches: "main"

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    # services:
    #   mysql:
    #     image: mysql:8.0
      # env:
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      # MYSQL_DATABASE: laravel
      # ports:
      #  - 33306:3306
      #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3
      #- name: Copy .env
      #run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftpupload.net
          username: mseet_36818940
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /